name: Java CI and Release

on:
  push:
    branches: ['main', 'master']
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-release:
    name: Build and Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'microsoft'
          cache: maven

      - name: Set vars
        id: vars
        run: |
          export TZ='Asia/Shanghai'
          echo "hash=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
          echo "time=$(git log -1 --format=%cd --date=format-local:%Y.%m.%d.%H%M)" >> $GITHUB_OUTPUT

      - name: Build with Maven
        run: mvn -B package --file pom.xml -DskipTests -Dapp.version=${{ steps.vars.outputs.hash }}

      - name: Rename artifact
        run: mv target/*.jar target/app-${{ steps.vars.outputs.hash }}.jar

      - name: Auto Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.vars.outputs.time }}-${{ steps.vars.outputs.hash }}
          name: Release-${{ steps.vars.outputs.hash }}
          draft: false
          prerelease: false
          files: target/app-${{ steps.vars.outputs.hash }}.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
